(define (iterate f x n)
  (define (folded f i reshead restail)
    (if (<= n i)
        (reverse (cons reshead restail))
        (folded f (+ i 1) (f reshead) (cons reshead restail))
        )
    )
  (if (= n 0)
      (list)
      (folded f 1 x (list))
  )
  )