(define (delete pred? xs)
  (define (folded pred? new old)
    (if (null? old)
        (reverse new)
        (if (pred? (car old))
            (folded pred? new (cdr old))
            (folded pred? (append (list (car old)) new) (cdr old))))
    )
  (folded pred? (list) xs)
  )